version: '3.8'

services:
  petclinic:
    build: .
    image: spring-petclinic:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=mysql
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/petclinic
      - SPRING_DATASOURCE_USERNAME=petclinic
      - SPRING_DATASOURCE_PASSWORD=petclinic
      - SPRING_JPA_HIBERNATE_DDL-AUTO=update
    depends_on:
      - mysql
      - postgres

  mysql:
    image: mysql:8.1
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=petclinic
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  postgres:
    image: postgres:15.4
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=petclinic
      - POSTGRES_USER=petclinic
      - POSTGRES_PASSWORD=petclinic
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U petclinic -d petclinic"]
      interval: 5s
      timeout: 5s
      retries: 5
