apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"  # Use values.yaml image
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          env:
            - name: MYSQL_USER
              value: {{ .Values.mysql.username }}  # Use values.yaml MySQL user
            - name: MYSQL_PASSWORD
              value: {{ .Values.mysql.password }}  # Use values.yaml MySQL password
            - name: MYSQL_DB
              value: {{ .Values.mysql.database }}  # Use values.yaml MySQL database name
